[package]
name = "ctftool"
version = "0.2.0"
authors = ["mephi42 <mephi42@gmail.com>"]
edition = "2021"

[dependencies]
anyhow = "1.0.44"
clap = { version = "3.2.20", features = ["derive"] }
cookie = "0.15.1"
cookie_store = "0.15.0"
console = "0.15.0"
env_logger = "0.9.0"
futures = "0.3.17"
hex = "0.4.3"
indicatif = "0.16.2"
lazy_static = "1.4.0"
log = "0.4.14"
regex = "1.5.4"
reqwest = { version = "0.11.11", features = ["json", "multipart"] }
rpassword = "5.0.1"
serde = { version = "1.0.130", features = ["derive"] }
serde_yaml = "0.8.21"
sha2 = "0.9.8"
time = "0.3.3"
tokio = { version = "1.12.0", features = ["fs", "macros", "rt-multi-thread"] }
url = "2.2.2"

[dev-dependencies]
assert_cmd = "2.0.2"
hyper = { version = "0.14.13", features = ["server"] }
tempdir = "0.3.7"

[lib]
path = "src/lib.rs"

[[bin]]
name = "ctf"
path = "src/main.rs"
