[package]
name = "ctftool"
version = "0.1.0"
authors = ["mephi42 <mephi42@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0.25"
# use git version for derive feature
clap = { git = "https://github.com/clap-rs/clap" }
lazy_static = "1.4.0"
# use git version for async feature
reqwest = { git = "https://github.com/seanmonstar/reqwest.git", features = ["json"] }
serde = { version = "1.0.104", features = ["derive"] }
serde_yaml = "0.8.11"
tokio = { version = "0.2.6", features = ["fs", "macros"] }
url = "2.1.0"

[dev-dependencies]
assert_cmd = "0.12.0"
hyper = "0.13.1"
tempdir = "0.3.7"

[[bin]]
name = "ctf"
path = "src/main.rs"
