[package]
name = "ctftool"
version = "0.2.0"
authors = ["mephi42 <mephi42@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0.26"
# use git version for derive feature
clap = { git = "https://github.com/clap-rs/clap" }
cookie = "0.12.0"
cookie_store = "0.10.0"
console = "0.9.2"
env_logger = "0.7.1"
futures = "0.3.4"
hex = "0.4.2"
indicatif = "0.14.0"
lazy_static = "1.4.0"
log = "0.4.8"
regex = "1.3.4"
# use git version for async feature
reqwest = { git = "https://github.com/seanmonstar/reqwest.git", features = ["json"] }
rpassword = "4.0.5"
serde = { version = "1.0.104", features = ["derive"] }
serde_yaml = "0.8.11"
sha2 = "0.8.1"
time = "0.1.42"
tokio = { version = "0.2.13", features = ["fs", "macros"] }
url = "2.1.1"

[dev-dependencies]
assert_cmd = "0.12.0"
hyper = "0.13.3"
tempdir = "0.3.7"

[lib]
path = "src/lib.rs"

[[bin]]
name = "ctf"
path = "src/main.rs"
