services:
  main:
    build:
      context: ./image
    volumes:
      - $PWD:$PWD
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY
      - NO_AT_BRIDGE=1  # Couldn't connect to accessibility bus
      - PWNLIB_NOTERM=1
      - PYTHONIOENCODING=utf-8
    working_dir: $PWD
    init: true
    command: sleep inf
